import type { Scenario } from '../shared/types.js';

// Original fictional clues. This file is server-only: answers never ship in the client bundle.
export const scenarios: Scenario[] = [
  { id:'battery-01', category:'Battery / electrical', title:'“My dashboard throws a disco, but the engine won’t join in.”', vehicle:'A compact hatchback after a frosty weekend', clues:['The starter clicks rapidly instead of turning the engine.','The headlights become very dim when you try to start.','A jump-start gets the engine running.'], choices:['A weak battery','An empty washer bottle','Overinflated tires','A loose exhaust shield'], correct:0, explanation:'Starting needs a big burst of electrical power. Dim lights, rapid clicks, and a successful jump-start point to a weak battery.', difficulty:'easy' },
  { id:'battery-02', category:'Battery / electrical', title:'“The battery light is on. I just bought a battery!”', vehicle:'A delivery van halfway through its route', clues:['The engine started normally this morning.','The battery warning appeared while driving.','The charging unit should replenish the battery, but its output is low.'], choices:['The fuel cap is loose','The alternator isn’t charging','The rear tires are worn','The air filter is dusty'], correct:1, explanation:'The alternator replenishes electrical power while the engine runs. A new battery can still go flat if the alternator is not charging.', difficulty:'medium' },
  { id:'battery-03', category:'Battery / electrical', title:'“One headlight has decided to work part-time.”', vehicle:'An older coupe on a rainy evening', clues:['Only the left headlight flickers.','The other lights stay bright.','Moving the loose connector behind that headlight makes it work again.'], choices:['An empty fuel tank','A failing radiator','A loose headlight connection','A worn brake pad'], correct:2, explanation:'A problem confined to one light, which changes when its connector moves, points to that electrical connection.', difficulty:'easy' },
  { id:'starting-01', category:'Engine starting', title:'“The engine spins enthusiastically. That’s all it does.”', vehicle:'A small wagon at the end of a long road trip', clues:['The starter turns the engine at its usual speed.','The fuel gauge is below empty.','Adding fuel lets the engine start.'], choices:['A punctured tire','A flat key-fob battery','A stuck window','An empty fuel tank'], correct:3, explanation:'The starter has power, but the engine needs fuel to run. The empty gauge and successful refill supply the answer.', difficulty:'easy' },
  { id:'starting-02', category:'Engine starting', title:'“My car says it can’t find the key. I’m holding it.”', vehicle:'A push-button-start city car', clues:['The dashboard says “Key not detected.”','The door-unlock button on the fob has also stopped working.','The spare fob starts the car normally.'], choices:['A flat key-fob battery','A blocked exhaust','Low engine oil','An overheated radiator'], correct:0, explanation:'The spare fob works, so the car can recognize a healthy key. The original fob’s weak battery explains both symptoms.', difficulty:'easy' },
  { id:'starting-03', category:'Engine starting', title:'“It won’t start until I wiggle the gear selector.”', vehicle:'An automatic sedan in a supermarket parking lot', clues:['The dashboard and headlights have normal power.','The starter is silent in Park but works in Neutral.','A safety switch only permits starting when it recognizes Park or Neutral.'], choices:['A broken horn','A gear-position safety switch fault','A low washer-fluid level','A nail in a tire'], correct:1, explanation:'The switch that recognizes Park or Neutral is the key clue. If it misreads Park, it can prevent the starter from operating.', difficulty:'medium' },
  { id:'cooling-01', category:'Cooling / overheating', title:'“There’s a sweet smell, and my hood is doing a kettle impression.”', vehicle:'A family wagon after a steep climb', clues:['Steam rises from the engine bay.','The temperature gauge is unusually high.','A sweet-smelling liquid is escaping from a radiator hose.'], choices:['A torn seat cover','An exhaust rattle','A coolant leak','A loose fuel cap'], correct:2, explanation:'Coolant carries heat away from the engine. A leaking cooling hose explains the sweet smell, steam, and rising temperature.', difficulty:'easy' },
  { id:'cooling-02', category:'Cooling / overheating', title:'“The car gets hot in traffic, then chills out on the open road.”', vehicle:'A compact SUV on a summer afternoon', clues:['Temperature rises while stopped.','Moving air at road speed brings it back down.','The radiator’s electric fan never turns on.'], choices:['The stereo is too loud','The oil is overfilled','The tires are too soft','The radiator fan isn’t working'], correct:3, explanation:'At a stop, the fan must move air through the radiator. Road-speed airflow can hide a fan failure.', difficulty:'medium' },
  { id:'cooling-03', category:'Cooling / overheating', title:'“The engine warms up, but the heat never reaches the radiator.”', vehicle:'A vintage pickup on a short drive', clues:['The engine temperature climbs rapidly.','The radiator stays cool even as the engine gets too hot.','A thermostat valve is supposed to open and let hot coolant reach the radiator.'], choices:['A thermostat stuck closed','A burned-out dome light','A loose wheel cover','A clogged washer nozzle'], correct:0, explanation:'A closed thermostat blocks the coolant route to the radiator. The engine gets hot while the radiator stays cool.', difficulty:'hard' },
  { id:'tires-01', category:'Tires / brakes', title:'“The steering wheel shimmies every time I slow down.”', vehicle:'A highway commuter sedan', clues:['The vibration happens only when braking.','The brake pedal pulses at the same time.','Inspection finds uneven surfaces on the front brake discs.'], choices:['A weak battery','Uneven front brake discs','An empty fuel tank','A loose gas cap'], correct:1, explanation:'Uneven brake-disc surfaces can vary the braking force, producing pedal pulses and steering vibration when the brakes are applied.', difficulty:'medium' },
  { id:'tires-02', category:'Tires / brakes', title:'“One tire looks like it skipped breakfast.”', vehicle:'A little hatchback parked overnight', clues:['One tire is visibly flatter than the others.','The pressure warning is on.','A small nail is embedded in that tire’s tread.'], choices:['A weak starter motor','A coolant leak','A tire puncture','A broken radio antenna'], correct:2, explanation:'The embedded nail and pressure loss identify a puncture. The warning light is reporting the resulting low tire pressure.', difficulty:'easy' },
  { id:'tires-03', category:'Tires / brakes', title:'“My brakes have started announcing every stop.”', vehicle:'A well-traveled city car', clues:['A high-pitched squeal appears during braking.','The brake pads are worn very thin.','A small metal wear tab is touching the brake disc.'], choices:['Too much fuel','A dirty windshield','An open glove box','Worn brake pads'], correct:3, explanation:'A brake-pad wear tab is designed to make noise when the pad becomes thin. These clues point directly to worn pads.', difficulty:'easy' },
  { id:'fluids-01', category:'Fluids / leaks', title:'“My parked car has left a tiny pond. Should I panic?”', vehicle:'A crossover after using the air conditioning', clues:['The puddle is clear and has no smell.','It appears under the passenger side after the AC runs.','All fluid levels remain normal.'], choices:['Normal air-conditioning condensation','A fuel leak','A brake-fluid leak','An engine-oil leak'], correct:0, explanation:'Air conditioning removes moisture from the air and drains it under the car. Clear, odorless water after AC use is normal condensation.', difficulty:'easy' },
  { id:'fluids-02', category:'Fluids / leaks', title:'“The driveway has a dark, slippery new signature.”', vehicle:'An older hatchback after an overnight park', clues:['The liquid is brown-black and oily.','It drips from the bottom of the engine.','The engine-oil level slowly drops.'], choices:['Rainwater from the roof','An engine-oil leak','A washer-fluid leak','Air-conditioning condensation'], correct:1, explanation:'The texture, location, and falling oil level all point to leaking engine oil.', difficulty:'easy' },
  { id:'fluids-03', category:'Fluids / leaks', title:'“The washers make noise, but my windshield stays dusty.”', vehicle:'A small van after a muddy weekend', clues:['You can hear the washer pump when you press the control.','The washer reservoir is empty.','Refilling it restores the spray, and the level then stays steady.'], choices:['A dead alternator','Worn brake discs','An empty washer-fluid reservoir','An overheated engine'], correct:2, explanation:'The pump was operating but had no liquid to spray. Refilling the reservoir fixes the problem.', difficulty:'easy' },
  { id:'funny-01', category:'Odd customer complaints', title:'“My car sounds like a shopping cart arguing with a tambourine.”', vehicle:'A cheerful old wagon on a bumpy lane', clues:['A thin metallic rattle comes from underneath.','The engine runs smoothly.','A technician finds a loose metal cover around the exhaust.'], choices:['A flat battery','An empty coolant tank','A broken speedometer','A loose exhaust heat shield'], correct:3, explanation:'The thin protective heat shield can rattle against the exhaust when its fasteners loosen. The loose cover is the giveaway.', difficulty:'medium' },
  { id:'funny-02', category:'Odd customer complaints', title:'“Something rolls around the trunk every time I turn.”', vehicle:'A compact coupe after a grocery run', clues:['The clunk moves from left to right on corners.','The noise stops when the trunk is emptied.','A loose soup can is found behind a bag.'], choices:['Loose cargo in the trunk','A failed alternator','A blocked radiator','An engine timing problem'], correct:0, explanation:'Sometimes the simplest diagnosis wins. The noise follows the loose cargo and disappears when the trunk is empty.', difficulty:'easy' },
  { id:'funny-03', category:'Odd customer complaints', title:'“The car whistles like it’s trying to hail a taxi.”', vehicle:'A tall wagon with a roof rack', clues:['The whistle starts only at higher speeds.','There are no engine warning lights.','Removing the roof rack’s loose end cap stops the sound.'], choices:['A worn brake pad','Air whistling through the roof rack','An empty battery','A radiator leak'], correct:1, explanation:'Air rushing past the loose roof-rack cap produces the whistle. Its disappearance after removing the cap confirms the source.', difficulty:'medium' },
  { id:'general-01', category:'General car knowledge', title:'“The check-engine light appeared right after my fuel stop.”', vehicle:'A compact sedan after filling up', clues:['The engine still runs normally.','The fuel cap is hanging loose.','The diagnostic code reports a leak in the system that traps fuel vapor.'], choices:['A burned-out headlight','A punctured tire','A loose fuel cap','A blocked cabin filter'], correct:2, explanation:'A loose fuel cap can let vapor escape from the sealed fuel system and trigger a leak warning.', difficulty:'medium' },
  { id:'general-02', category:'General car knowledge', title:'“The fan is loud, but the cabin barely gets a breeze.”', vehicle:'A family SUV after a dusty camping trip', clues:['The cabin fan motor sounds normal.','Airflow is weak at every dashboard vent.','The filter that incoming cabin air passes through is packed with dust and leaves.'], choices:['A low fuel level','A loose wheel nut','A damaged key fob','A clogged cabin-air filter'], correct:3, explanation:'The cabin filter sits in the ventilation airflow. When it fills with debris, it restricts the air even though the fan keeps running.', difficulty:'medium' }
];
