import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronRight, Copy, Flag, Gauge, Link, Radio, Timer, Trophy, Users, Volume2, VolumeX, Wrench, X, Zap } from 'lucide-react';
import type { PublicPlayer, RoomView } from '../shared/types';
import { useGame } from './useGame';

const number=(n:number)=>n.toLocaleString();
function Dial({seconds=20,progress=1,staticDial=false}:{seconds?:number;progress?:number;staticDial?:boolean}){
  return <div className={`dial ${seconds<=5&&!staticDial?'urgent':''}`}>
    <svg viewBox="0 0 160 160" aria-hidden="true"><circle className="dial-track" cx="80" cy="80" r="69"/><circle className="dial-value" cx="80" cy="80" r="69" pathLength="100" strokeDasharray={`${Math.max(0,progress)*100} 100`}/><circle className="dial-inner" cx="80" cy="80" r="55"/></svg>
    <div className="dial-text"><strong data-testid="countdown">{seconds.toString().padStart(2,'0')}</strong><span>SECONDS</span></div>
  </div>;
}
function Leaderboard({state,final=false}:{state:RoomView;final?:boolean}){
  return <section className="board panel" aria-label={final?'Final leaderboard':'Leaderboard'}>
    <div className="panel-heading"><h2>{final?'Final standings':'The leaderboard'}</h2><span className="eyebrow">{final?'FINISH LINE':'LIVE SCORES'}</span></div>
    <ol className="ranking">{state.players.map(p=><li key={p.id} className={p.id===state.youId?'is-you':''}>
      <span className="rank">{p.rank.toString().padStart(2,'0')}</span><span className="avatar">{p.name.slice(0,2).toUpperCase()}</span>
      <div className="player-label"><strong>{p.name}{p.id===state.youId&&<small> YOU</small>}</strong><span>{p.id===state.hostId?'Host · ':''}{p.connected?'In the garage':'Reconnecting'}{p.result&&` · ${p.result==='correct'?'Correct':p.result==='incorrect'?'Incorrect':'No answer'}`}</span></div>
      <div className="score"><strong>{number(p.score)}</strong>{p.result&&<span className={p.roundPoints?'positive':''}>+{number(p.roundPoints)} this round</span>}</div>
    </li>)}</ol>
  </section>;
}
function Podium({players}:{players:PublicPlayer[]}){
  const top=players.filter(p=>p.rank<=3);
  // Tied players share a rank and are all represented, rather than being arbitrarily omitted.
  return <div className="podium">{top.map(p=><div key={p.id} className={`podium-place place-${p.rank}`}>
    <span className="podium-avatar">{p.rank===1?<Trophy size={28}/>:p.name.slice(0,2).toUpperCase()}</span>
    <strong>{p.name}</strong><span>{number(p.score)} pts</span><div className="podium-step"><span>{p.rank===1?'1st':p.rank===2?'2nd':'3rd'}</span></div>
  </div>)}</div>;
}
export default function App(){
  const game=useGame();const {state,connected,pending,error,offset,request}=game;
  const [screen,setScreen]=useState<'home'|'create'|'join'>(new URLSearchParams(location.search).has('room')?'join':'home');
  const [name,setName]=useState('');const [code,setCode]=useState(new URLSearchParams(location.search).get('room')?.toUpperCase().slice(0,5)||'');
  const [now,setNow]=useState(Date.now());const [copied,setCopied]=useState('');const [muted,setMuted]=useState(true);
  const audio=useRef<AudioContext|null>(null);const heading=useRef<HTMLHeadingElement>(null);const previousPhase=useRef('');
  const host=state?.hostId===state?.youId;const you=state?.players.find(p=>p.id===state.youId);
  const remaining=state?Math.max(0,state.deadline-(now+offset)):20_000;
  const seconds=Math.ceil(remaining/1000);const isQuestion=state?.phase==='question';
  const connectionText=connected?'Connected':'Connecting…';
  function beep(freq=660){if(muted || !audio.current)return;const ctx=audio.current;void ctx.resume();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.frequency.value=freq;gain.gain.setValueAtTime(.04,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.12);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.12);}
  async function choose(choice:number){if(!state||pending||!connected||remaining<=0)return;if(await request('answer',{choice,roundId:state.roundId}))beep();}
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),100);return()=>clearInterval(timer);},[]);
  useEffect(()=>{
    const phase=`${state?.phase??screen}-${state?.round??0}`;
    if(previousPhase.current!==phase){heading.current?.focus();previousPhase.current=phase;if(state?.phase==='reveal')beep(880);}
  },[state?.phase,state?.round,screen]);
  useEffect(()=>{
    function key(e:KeyboardEvent){if(e.altKey||e.ctrlKey||e.metaKey||e.repeat||!isQuestion||/INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement)?.tagName))return;const n=Number(e.key);if(n>=1&&n<=4){e.preventDefault();void choose(n-1);}}
    window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);
  });
  async function copy(text:string,label:string){try{await navigator.clipboard.writeText(text);setCopied(label);setTimeout(()=>setCopied(''),2500);}catch{setCopied('Select and copy the link below.');}}
  function show(target:typeof screen){game.setError('');setScreen(target);}
  const roomLink=state?`${location.origin}/?room=${state.code}`:'';
  const titleProps={ref:heading,tabIndex:-1};
  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="Garage Gauntlet home"><span className="brand-icon"><Wrench size={22}/></span><span>GARAGE<span className="brand-light"> GAUNTLET</span></span></a><div className="top-actions"><span className={`connection ${connected?'online':''}`}><i/>{connectionText}</span><button className="icon-button" aria-label={muted?'Turn sound on':'Mute sound'} aria-pressed={!muted} onClick={()=>{if(muted){try{audio.current??=new AudioContext();void audio.current.resume();}catch{return;}}setMuted(!muted);}}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button></div></header>
    <main>
      {!connected&&state&&<div className="notice" role="status"><Radio size={18}/>Connection interrupted. Reconnecting automatically… The round keeps running.</div>}
      {error&&<div className="error" role="alert"><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>game.setError('')}><X size={18}/></button></div>}
      {!state&&screen==='home'&&<>
        <div className="home-grid">
          <section className="intro"><div className="eyebrow orange"><span className="tiny-square"/> THE GARAGE IS OPEN</div><h1 {...titleProps}>GARAGE<br/><span>GAUNTLET</span><span className="title-period">.</span></h1><p className="tagline">Diagnose it or lose it.</p><p className="intro-copy">Strange noises. Questionable smells.<br/>One right diagnosis. Beat your friends to it.</p><div className="home-buttons"><button className="button primary" onClick={()=>show('create')}>Create Room <ArrowRight size={19}/></button><button className="button secondary" onClick={()=>show('join')}>Join Room <Users size={19}/></button></div><p className="spec-line">2–12 players <span>•</span> About 10 minutes <span>•</span> No app needed</p></section>
          <section className="mission-panel panel"><div className="bay-heading"><span className="eyebrow">TONIGHT’S CHALLENGE</span><span className="bay">BAY / 01</span></div><div className="mission-main"><Dial staticDial/><div><div className="eyebrow orange">THINK FAST. FIX FASTER.</div><h2>Got a good<br/>diagnosis?</h2><p>The clues do the heavy lifting.<br/>No mechanic’s license required.</p></div></div><div className="mission-specs"><div><strong>10</strong><span>ROUNDS</span></div><div><strong>20</strong><span>SCENARIOS</span></div><div><strong>01</strong><span>WINNING CREW</span></div></div><div className="mission-bottom"><Flag size={17}/><span>Quick answers. Big points. Bragging rights.</span></div></section>
        </div>
        <section className="how-to" aria-label="How to play"><div><span className="step-no">01</span><div><h2>Assemble your crew</h2><p>Create a room. Share the code.</p></div><Users size={23}/></div><div><span className="step-no">02</span><div><h2>Read the symptoms</h2><p>Follow the clues. Pick a diagnosis.</p></div><Wrench size={23}/></div><div><span className="step-no">03</span><div><h2>Race up the ranks</h2><p>Fast + correct = more points.</p></div><Trophy size={23}/></div></section>
      </>}
      {!state&&screen!=='home'&&<div className="setup-wrap"><button className="text-button" onClick={()=>show('home')}><ArrowLeft size={17}/> Back to the garage</button><section className="setup panel"><div className="eyebrow orange">{screen==='create'?'YOU’RE IN THE DRIVER’S SEAT':'YOUR CREW IS WAITING'}</div><h1 {...titleProps}>{screen==='create'?'Open a garage.':'Join the crew.'}</h1><p>{screen==='create'?'You’ll host the game and play along.':'Enter the code your host shared with you.'}</p><form onSubmit={e=>{e.preventDefault();void request(screen==='create'?'create':'join',{name,code});}}>{screen==='join'&&<label>Room code<input autoComplete="off" autoCapitalize="characters" spellCheck={false} className="code-input" placeholder="ABCDE" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,5))} required minLength={5} maxLength={5}/></label>}<label>Your display name<input autoComplete="off" placeholder="e.g. Turbo Toast" value={name} onChange={e=>setName(e.target.value)} maxLength={18} required/></label><p className="field-hint">A nickname is perfect. No account needed.</p><button className="button primary full-width" disabled={pending||!connected}>{pending?'Connecting…':screen==='create'?'Create Room':'Join Game'}<ArrowRight size={19}/></button></form><div className="setup-foot"><Users size={16}/> 2–12 players <span>·</span> 10 rounds <span>·</span> 20 seconds each</div></section></div>}
      {state?.phase==='lobby'&&<>
        <div className="page-heading"><div><div className="eyebrow orange">{host?'HOST LOBBY':'YOU’RE IN'}</div><h1 {...titleProps}>{host?'Gather your pit crew.':'You’re on the team.'}</h1><p>{host?'Share the code, then fire up the first round.':`Welcome, ${you?.name}. Waiting for the host to start.`}</p></div><span className="status-pill"><span className="pulse-dot"/> LOBBY OPEN</span></div>
        <div className="lobby-grid"><section className="room-invite panel"><div className="eyebrow">YOUR ROOM CODE</div><strong className="room-code" data-testid="room-code">{state.code}</strong><button className="button secondary full-width" onClick={()=>void copy(roomLink,'Join link copied')}><Copy size={17}/>{copied||'Copy join link'}</button><label className="share-url">Or share this link<input aria-label="Room join link" value={roomLink} readOnly onFocus={e=>e.target.select()}/></label><div className="lobby-rule"><Timer size={19}/><span>10 rounds. 20 seconds each.<br/>Correct answers score 500–1,000 points.</span></div></section><section className="crew panel"><div className="panel-heading"><h2>In the garage</h2><span className="count-chip">{state.players.length} / 12</span></div><ul>{state.players.map(p=><li key={p.id}><span className="avatar">{p.name.slice(0,2).toUpperCase()}</span><strong>{p.name} {p.id===state.youId&&<small>YOU</small>}</strong><span className="crew-role">{!p.connected?'Reconnecting':p.id===state.hostId?'Host':'Ready'}</span><span className={`presence ${p.connected?'ready':''}`}/></li>)}</ul><div className="crew-start">{host?<><button className="button primary full-width" disabled={pending||!connected||state.players.filter(p=>p.connected).length<2} onClick={()=>void request('start')}>Start Game <Flag size={19}/></button><p>{state.players.filter(p=>p.connected).length<2?'Waiting for at least one more player…':'Everyone in? Let’s make some questionable diagnoses.'}</p></>:<div className="waiting"><Radio size={21}/><p>Waiting for the host to start…<small>The first round will appear automatically.</small></p></div>}</div></section></div>
      </>}
      {state&&isQuestion&&state.question&&<>
        <div className="round-top"><div className="round-label"><span className="eyebrow orange">DIAGNOSTIC CHALLENGE</span><h1 {...titleProps}>Round {state.round}<span> / {state.totalRounds}</span></h1></div><div className="round-room"><span>ROOM</span><strong>{state.code}</strong></div><div className="your-score"><span>YOUR SCORE</span><strong>{number(you?.score??0)} <small>PTS</small></strong></div></div>
        <div className="round-progress" aria-label={`Round ${state.round} of ${state.totalRounds}`}>{Array.from({length:state.totalRounds},(_,i)=><i key={i} className={i<state.round?'filled':''}/>)}</div>
        <div className="question-grid"><section className="diagnostic panel"><div className="question-meta"><span className="category"><Wrench size={15}/>{state.question.category}</span><span className="difficulty">{state.question.difficulty}</span></div><div className="eyebrow muted">CUSTOMER COMPLAINT</div><h2>{state.question.title}</h2><p className="vehicle">{state.question.vehicle}</p><div className="clue-heading"><Gauge size={17}/><h3>Under the hood</h3><span>{state.question.clues.length} CLUES</span></div><ol className="clues">{state.question.clues.map((clue,i)=><li key={clue}><span>{(i+1).toString().padStart(2,'0')}</span><p>{clue}</p></li>)}</ol></section><aside className="timer-panel panel"><div className="eyebrow">TIME TO DIAGNOSE</div><Dial seconds={seconds} progress={remaining/state.roundMs}/><p className={seconds<=5?'orange':''}>{seconds===0?'Time’s up. Checking results…':seconds<=5?'Last call. Make it count.':'The clock is ticking.'}</p><div className="answers-in"><Users size={18}/><strong>{state.submitted} / {state.players.length}</strong><span>answers in</span></div></aside></div>
        <section className="answer-section" aria-label="Choose your diagnosis"><div className="answer-heading"><h2>What’s the diagnosis?</h2><span>ONE ANSWER · CHANGE IT UNTIL TIME RUNS OUT</span></div><div className="answers">{state.question.choices.map((answer,i)=><button key={i} data-testid={`answer-${i}`} className={`answer ${state.ownAnswer===i?'selected':''}`} aria-pressed={state.ownAnswer===i} disabled={!connected||pending||remaining<=0} onClick={()=>void choose(i)}><span className="answer-letter">{'ABCD'[i]}</span><strong>{answer}</strong>{state.ownAnswer===i?<CheckCircle2 size={21}/>:<span className="answer-key">{i+1}</span>}</button>)}</div><div className={`answer-confirm ${state.ownAnswer!==null?'confirmed':''}`} role="status">{state.ownAnswer!==null?<><Check size={17}/>Answer locked in. You can still change it before time expires.</>:<><Zap size={17}/>Pick your answer. Faster correct diagnoses earn more points.</>}</div></section>
      </>}
      {state?.phase==='reveal'&&state.question&&state.reveal&&<>
        <div className="page-heading"><div><div className="eyebrow orange">ROUND {state.round} / {state.totalRounds} · RESULTS</div><h1 {...titleProps}>{you?.result==='correct'?'Nailed the diagnosis.':'Every round is a fresh start.'}</h1><p>{you?.result==='correct'?`You earned ${number(you.roundPoints)} points. Nice work under pressure.`:you?.result==='incorrect'?'That one got away. Here’s what the clues were telling you.':'No answer submitted this time. Here’s the diagnosis.'}</p></div><span className="round-earned">+{number(you?.roundPoints??0)}<small>POINTS</small></span></div>
        <div className="results-grid"><section className="reveal panel"><div className="eyebrow positive"><CheckCircle2 size={17}/> CORRECT DIAGNOSIS</div><h2>{state.question.choices[state.reveal.correct]}</h2><p>{state.reveal.explanation}</p><div className="your-answer"><span>YOUR ANSWER</span><strong>{state.ownAnswer===null?'No answer':state.question.choices[state.ownAnswer]}</strong></div><div className="next-action">{host?<button className="button primary full-width" disabled={pending||!connected} onClick={()=>void request('next',{roundId:state.roundId})}>{state.round===state.totalRounds?'See Final Results':'Next Round'}<ArrowRight size={19}/></button>:<p className="waiting-text"><Radio size={18}/>Waiting for the host to continue…</p>}</div></section><Leaderboard state={state}/></div>
      </>}
      {state?.phase==='final'&&<><section className="final-heading"><div className="eyebrow orange"><Flag size={17}/> THE GAUNTLET IS COMPLETE</div><h1 {...titleProps}>{state.players.filter(p=>p.rank===1).length>1?'A photo finish.':'Garage royalty.'}</h1><p>{state.players.filter(p=>p.rank===1).map(p=>p.name).join(' & ')} {state.players.filter(p=>p.rank===1).length>1?'share the crown.':'takes the crown.'} Ten rounds. Bragging rights secured.</p><Podium players={state.players}/></section><div className="final-grid"><Leaderboard state={state} final/><section className="replay panel"><Trophy size={27} className="orange"/><h2>Another lap?</h2><p>Same crew. Fresh shuffle.<br/>Scores reset to zero.</p>{host?<button className="button primary full-width" disabled={pending||!connected||state.players.filter(p=>p.connected).length<2} onClick={()=>void request('start')}>Play Again <ArrowRight size={19}/></button>:<p className="waiting-text">Waiting for the host to play again.</p>}<button className="button secondary full-width" onClick={()=>void copy(location.origin,'Game link copied')}><Link size={17}/>{copied||'Share the game'}</button><input className="share-game-url" aria-label="Game link" readOnly value={location.origin} onFocus={e=>e.target.select()}/></section></div></>}
      {state&&<div className="room-footer"><span><Users size={15}/>{state.players.filter(p=>p.connected).length} connected <span>·</span> Room {state.code}</span><button className="text-button" onClick={game.leave}><ArrowLeft size={14}/>Leave room</button></div>}
    </main>
    <footer className="site-footer"><span><span className="tiny-square"/> BUILT FOR FRIENDLY COMPETITION</span><span>Fictional car trouble. Real bragging rights.</span></footer>
  </div>;
}
